name: flutter_gp
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bdaya_custom_splash:
    git:
      url: https://github.com/Bdaya-Dev/custom-splash.git
      ref: master
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  file_picker: ^3.0.2+2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_screenutil: ^5.0.0+2
  get: 4.1.4
  pin_code_text_field: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIconTransparent.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Bold.ttf

